# Use the official Python image as a base image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the requirements.txt file and install dependencies
COPY requirements-usecase2.txt /app/

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements-usecase2.txt


ENV HF_HOME="/root/.cache/huggingface"

# Copy the rest of the application code
COPY . /app

RUN --mount=type=cache,target=/root/.cache/huggingface \
    python /app/preload_models_usecase2.py

# Run the consumer
CMD ["python", "run_consumer_usecase2.py"]
