FROM python:3.12-slim

WORKDIR /app

COPY requirements*.txt ./

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt -r requirements-test.txt

COPY . .

ENV PYTHONPATH=/app

CMD ["pytest", "--cov=app", "tests/"]