# Use the official Python image as a base image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the requirements.txt file and install dependencies
COPY requirements-usecase3.txt /app/

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements-usecase3.txt

COPY preload_models_usecase3.py /app/
ENV HF_HOME="/root/.cache/huggingface"
RUN python /app/preload_models_usecase3.py

# Copy the rest of the application code
COPY . /app

# Run the consumer
CMD ["python", "run_consumer_usecase3.py"]
