# Use the official Python image as a base image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the requirements.txt file and install dependencies
COPY requirements-genai.txt /app/
RUN pip install --no-cache-dir -r requirements-genai.txt

# Copy the rest of the application code
COPY . /app

# Run the consumer
CMD ["python", "run_consumer.py"]

