name: Build and push Docker images (Flask and React app)

# currently only flask web app and react images are being built and pushed
# The disk space provided by GitHub Actions is limited to 10GB for free plan, models are too large for this space

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build flask Docker image
        working-directory: backend
        run: |
          docker build -f Dockerfile -t ${{ vars.DOCKERHUB_USERNAME }}/flask_mediainsight:latest .

      - name: Push flask Docker image
        working-directory: backend
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/flask_mediainsight:latest

      - name: Build react Docker image
        working-directory: frontend/mediainsight_ui
        run: |
          docker build -f Dockerfile -t ${{ vars.DOCKERHUB_USERNAME }}/react_mediainsight:latest .

      - name: Push react Docker image
        working-directory: frontend/mediainsight_ui
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/react_mediainsight:latest
