name: Backend Tests

on:
  push:
    branches: ['*']
    paths:
      - 'backend/**'
      - '.github/workflows/test-backend.yml'
  pull_request:
    branches: ['*']
    paths:
      - 'backend/**'
      - '.github/workflows/test-backend.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
      image: mongodb/mongodb-community-server:latest
      ports:
          - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: mongoadmin
        MONGO_INITDB_ROOT_PASSWORD: mongosecret

    kafka:
      image: bitnami/kafka:latest
      ports:
          - 9092:9092
          - 9093:9093
          - 9094:9094
      environment:
        KAFKA_CFG_NODE_ID: 1
        KAFKA_CFG_PROCESS_ROLES: broker,controller
        KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
        KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
        KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:9094
        KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
        KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
        ALLOW_PLAINTEXT_LISTENER: "yes"
      volumes:
        - kafka_data:/bitnami/kafka/data
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          
      - name: Run tests
        working-directory: ./backend
        env:
          MONGODB_URL: mongodb://localhost:27017
          KAFKA_BOOTSTRAP_SERVERS: localhost:9092
          PYTHONPATH: ${{ github.workspace }}/backend
        run: |
          pytest tests/ --cov=app --cov-report=xml
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./backend/coverage.xml
          flags: backend
          name: backend-coverage
          fail_ci_if_error: true